# Generated by Django 4.1.1 on 2022-10-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_inner_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('brand', models.CharField(max_length=70)),
                ('details', models.CharField(max_length=70)),
                ('guarantee', models.CharField(max_length=70)),
                ('shipping', models.CharField(max_length=70)),
                ('price', models.PositiveSmallIntegerField()),
                ('discount', models.PositiveSmallIntegerField()),
                ('instock', models.PositiveSmallIntegerField()),
                ('min_order', models.CharField(default='', max_length=30)),
                ('inner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.inner')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product')),
            ],
        ),
    ]
