# Generated by Django 4.1 on 2022-10-26 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_product_inner'),
        ('userapp', '0001_initial'),
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1)),
                ('total', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.profile')),
            ],
        ),
    ]
