# Generated by Django 4.1 on 2022-11-01 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
        ('ordersapp', '0004_rename_amount_shopcart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('items_total', models.PositiveSmallIntegerField()),
                ('shipping_fee', models.PositiveSmallIntegerField(default=5)),
                ('total', models.PositiveSmallIntegerField()),
                ('cart', models.ManyToManyField(to='ordersapp.shopcart')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.profile')),
            ],
        ),
    ]
