# Generated by Django 4.1 on 2022-11-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0008_rename_shopcart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='amount',
        ),
    ]
